#!/usr/bin/env node
/**
 * "Build" for a dependency-free static game: copy src/ to dist/, then bundle
 * shared/synthAudio.ts into an IIFE that audio.js bridges onto.
 * There is no full Vite/React stack here; BASE_URL rewriting is unnecessary
 * because every asset reference in src/index.html is already relative.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(dirname, 'src');
const outDir = path.join(dirname, 'dist');
const sharedSynth = path.resolve(dirname, '../../shared/synthAudio.ts');
const require = createRequire(path.resolve(dirname, '../../package.json'));
const bundledRel = path.join('js', 'clubhouse-synth-audio.js');

function copyRecursive(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const name of fs.readdirSync(src)) {
      copyRecursive(path.join(src, name), path.join(dest, name));
    }
    return;
  }
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

async function bundleSharedSynthAudio(destFile) {
  const esbuild = require('esbuild');
  const banner =
    '/* Generated by build.mjs from shared/synthAudio.ts — do not edit. */\n';
  await esbuild.build({
    entryPoints: [sharedSynth],
    outfile: destFile,
    bundle: true,
    format: 'iife',
    globalName: 'ClubhouseSynthAudio',
    platform: 'browser',
    target: ['es2018'],
    banner: { js: banner },
    logLevel: 'silent',
  });
}

if (!fs.existsSync(srcDir)) {
  console.error('Missing src/ directory');
  process.exit(1);
}
if (!fs.existsSync(sharedSynth)) {
  console.error('Missing shared/synthAudio.ts at', sharedSynth);
  process.exit(1);
}

// Refresh the bridge bundle in src/ first so copy picks it up for dist/.
await bundleSharedSynthAudio(path.join(srcDir, bundledRel));

fs.rmSync(outDir, { recursive: true, force: true });
copyRecursive(srcDir, outDir);

console.log('Puyo Puyo: copied src/ -> dist/ + bundled shared synthAudio');
