/**
 * The branch template pool: pure data, no engine logic. Authoring a new
 * template means adding an entry to BRANCH_TEMPLATES — engine.ts never needs
 * to change, which is the property the spec asks for explicitly (and the
 * property Roguelike-Snake's relic pool lacked: every relic there was a
 * bespoke engine branch, so nobody added any and two runs shared 72% of what
 * they carried).
 *
 * Every template's obstacle count is generated by `evenObstacles`, a small
 * layout helper local to this file. It exists only to keep authoring safe —
 * same-lane obstacles come out spaced at least MIN_SAME_LANE_SPACING apart by
 * construction — but the OUTPUT is a plain array baked in at module load, so
 * from the engine's point of view a template is exactly as "just data" as if
 * every offset had been typed by hand.
 */
import {
  LANE_COUNT,
  MIN_LEAD_IN,
  MIN_TRAIL_OUT,
  densityFloor,
  type BranchTemplate,
  type Obstacle,
  type ObstacleKind,
  type RewardKind,
  type SpeedTier,
} from './constants';

function evenObstacles(length: number, count: number, kinds: ObstacleKind[]): Obstacle[] {
  const start = MIN_LEAD_IN;
  const end = length - MIN_TRAIL_OUT;
  const span = Math.max(0, end - start);
  const step = count > 1 ? span / (count - 1) : 0;
  const out: Obstacle[] = [];
  for (let i = 0; i < count; i++) {
    out.push({
      offset: Math.round(start + step * i),
      lane: i % LANE_COUNT,
      kind: kinds[i % kinds.length],
    });
  }
  return out;
}

function template(
  id: string,
  name: string,
  speed: SpeedTier,
  reward: RewardKind,
  length: number,
  count: number,
  kinds: ObstacleKind[],
  unlockDistance: number,
): BranchTemplate {
  const floor = densityFloor(speed, reward);
  if (count < floor) {
    // A template authored below its own axis rules would be exactly the
    // silent-lie failure mode this repo has hit before: text (and here, the
    // pool itself) promising a rule the data does not actually keep. Fail at
    // import time rather than trusting every future author to do the algebra.
    throw new Error(`${id}: density ${count} is below the floor ${floor} for ${speed}/${reward}`);
  }
  return {
    id,
    name,
    speed,
    reward,
    rewardOffset: Math.round(length * 0.55),
    length,
    obstacles: evenObstacles(length, count, kinds),
    unlockDistance,
  };
}

export const BRANCH_TEMPLATES: BranchTemplate[] = [
  // ── Tier 0: available from the first junction ─────────────────────────────
  template('loose-track', '鬆道', 'decel', 'none', 780, 2, ['hurdle', 'wall'], 0),
  template('steady-rail', '常軌', 'hold', 'none', 820, 3, ['hurdle', 'beam', 'wall'], 0),
  template('sprint-track', '衝刺股道', 'accel', 'none', 820, 9, ['hurdle', 'wall', 'beam'], 0),
  template('supply-siding', '補給側線', 'decel', 'supply', 820, 3, ['wall', 'hurdle', 'beam'], 0),
  template('water-rail', '水源軌', 'hold', 'supply', 900, 5, ['hurdle', 'wall', 'beam', 'hurdle'], 0),

  // ── Tier 1: opens up once the run has some distance behind it ─────────────
  template('overdrive', '超馳道', 'accel', 'supply', 960, 11, ['hurdle', 'wall', 'beam'], 1400),
  template('quiet-siding', '靜側線', 'decel', 'score', 850, 4, ['wall', 'beam', 'hurdle'], 1400),
  template('ledger-rail', '計分軌', 'hold', 'score', 950, 6, ['beam', 'hurdle', 'wall'], 1400),
  template('brakeline', '煞車道', 'decel', 'none', 700, 1, ['wall'], 1400),
  template('crosscut', '橫切道', 'hold', 'none', 830, 3, ['beam', 'wall', 'hurdle'], 1400),

  // ── Tier 2: late-run, highest stakes ───────────────────────────────────────
  template('redline', '紅線道', 'accel', 'score', 1040, 12, ['hurdle', 'beam', 'wall'], 3000),
  template('floodgate', '溢洪道', 'accel', 'supply', 980, 11, ['wall', 'hurdle', 'beam'], 3000),
  template('graveyard-shift', '夜班軌', 'hold', 'supply', 900, 5, ['hurdle', 'wall', 'beam', 'wall'], 3000),
  template('last-chance', '末班道', 'decel', 'supply', 800, 3, ['beam', 'wall', 'hurdle'], 3000),

  // ── Widening the pool ──────────────────────────────────────────────────────
  //
  // Fourteen templates against a run that clears twenty to seventy junctions
  // meant a run was offered 95% of the pool and two runs repeated 62% of what
  // they took. That is the shape of the failure Roguelike-Snake shipped with —
  // 18 relics for 15 picks, 98% offered, 72% overlap — where every run is the
  // same run. These add variety in SHAPE (obstacle ordering and segment length)
  // at existing speed/reward tiers rather than inventing new tiers, so the
  // density floors and the balance conclusions above still hold.
  template('gravel-run', '碎石道', 'decel', 'none', 720, 2, ['beam', 'wall'], 0),
  template('long-tangent', '長直線', 'hold', 'none', 1000, 4, ['wall', 'hurdle'], 0),
  template('short-spur', '短岔線', 'accel', 'none', 700, 9, ['hurdle', 'beam'], 0),
  template('coal-siding', '運煤側線', 'decel', 'supply', 860, 3, ['hurdle', 'beam', 'wall'], 0),
  template('signal-box', '號誌所', 'hold', 'score', 900, 6, ['wall', 'beam', 'hurdle'], 1400),
  template('cutting', '塹道', 'accel', 'none', 880, 10, ['wall', 'beam', 'hurdle'], 1400),
  template('tank-track', '給水軌', 'hold', 'supply', 940, 5, ['beam', 'hurdle', 'wall'], 1400),
  template('switchback', '之字道', 'decel', 'score', 820, 4, ['beam', 'wall', 'hurdle', 'wall'], 1400),
  template('mainline-dash', '幹線衝刺', 'accel', 'score', 1080, 13, ['beam', 'wall', 'hurdle'], 3000),
  template('night-mail', '夜郵軌', 'hold', 'score', 980, 6, ['hurdle', 'beam', 'wall', 'beam'], 3000),
  template('breakwater', '防波道', 'accel', 'supply', 1000, 11, ['beam', 'hurdle', 'wall'], 3000),
  template('final-siding', '終端側線', 'decel', 'none', 760, 1, ['beam'], 3000),
];

export function eligibleTemplates(distance: number): BranchTemplate[] {
  return BRANCH_TEMPLATES.filter((t) => t.unlockDistance <= distance);
}

export const TEMPLATE_BY_ID: Record<string, BranchTemplate> = Object.fromEntries(
  BRANCH_TEMPLATES.map((t) => [t.id, t]),
);
