"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STORAGE_KEY = exports.SCORE_HP_BONUS = exports.SCORE_ESCAPE = exports.SCORE_BOSS = exports.SCORE_FLOOR = exports.SCORE_KILL = exports.SCORE_FRUIT = exports.SPIKE_ARMED = exports.SPIKE_CYCLE = exports.HEAL_COST = exports.REROLL_COST = exports.BOSS_FLOORS = exports.MAX_FLOOR = exports.HOURGLASS_BONUS_MS = exports.INVULN_MS = exports.BLOOD_DASH_INTERVAL = exports.DASH_INVULN_MS = exports.DASH_COOLDOWN_MS = exports.DASH_DISTANCE = exports.DASH_COST = exports.MAX_FRUITS = exports.CURSED_ENERGY = exports.ENERGY_REGEN_PER_TICK = exports.FRUIT_ENERGY = exports.BASE_MAX_ENERGY = exports.START_ENERGY = exports.START_HP = exports.HURT_SHRINK = exports.MIN_LENGTH = exports.START_LENGTH = exports.FLOOR_SPEEDUP_MS = exports.MIN_MOVE_MS = exports.BASE_MOVE_MS = exports.GRID = void 0;
/** Tunables for 蛇窟迴廊. Grid is square so the arena fits portrait and desktop alike. */
exports.GRID = 21;
exports.BASE_MOVE_MS = 150;
exports.MIN_MOVE_MS = 90;
exports.FLOOR_SPEEDUP_MS = 4;
exports.START_LENGTH = 4;
exports.MIN_LENGTH = 3;
exports.HURT_SHRINK = 3;
exports.START_HP = 3;
exports.START_ENERGY = 60;
exports.BASE_MAX_ENERGY = 100;
exports.FRUIT_ENERGY = 12;
/** Trickle so a stranded run can always rebuild a dash. */
exports.ENERGY_REGEN_PER_TICK = 0.15;
exports.CURSED_ENERGY = 40;
exports.MAX_FRUITS = 2;
exports.DASH_COST = 30;
exports.DASH_DISTANCE = 4;
exports.DASH_COOLDOWN_MS = 600;
exports.DASH_INVULN_MS = 300;
exports.BLOOD_DASH_INTERVAL = 4;
exports.INVULN_MS = 1200;
exports.HOURGLASS_BONUS_MS = 1200;
exports.MAX_FLOOR = 15;
exports.BOSS_FLOORS = [5, 10, 15];
exports.REROLL_COST = 4;
exports.HEAL_COST = 8;
exports.SPIKE_CYCLE = 3;
exports.SPIKE_ARMED = 1;
exports.SCORE_FRUIT = 10;
exports.SCORE_KILL = 25;
exports.SCORE_FLOOR = 100;
exports.SCORE_BOSS = 500;
exports.SCORE_ESCAPE = 2000;
exports.SCORE_HP_BONUS = 300;
exports.STORAGE_KEY = 'clubhouse:roguelike-snake:best';
